using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.SqlClient;

namespace COFFEE_SHOP.FORMS
{
    public partial class ADD_USER : DevExpress.XtraEditors.XtraForm
    {
        BL.TRANS TR = new BL.TRANS();
        BL.LOGIN LOG = new BL.LOGIN();
        void GET_ID()
        {
            DataTable DT = new DataTable();
            DT = TR.GET_USER_ID();
            int id = Convert.ToInt32(DT.Rows[DT.Rows.Count - 1][0]);
            TXT_ID.Text = id.ToString();
        }
        void CLEAR_TEXT_BOX(Control CN)
        {
            foreach (Control C in CN.Controls)
                if (C is TextBox)

                    ((TextBox)C).Clear();

                else

                    CLEAR_TEXT_BOX(C);
           
        }
        public ADD_USER()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }
        public void CLEAR()
        {
            TXT_FULLNAME.Text = "";
            TXT_ID.Text = "";
            TXT_NAME.Text = "";
            TXT_PASS.Text = "";
            TXT_REPASS.Text = "";
            combo_TYPE.Text = "";
        }
           
        private void simpleButton3_Click(object sender, EventArgs e)
        {
            Dispose();
            Close();
        }

        private void BT_SAVE_Click(object sender, EventArgs e)
        {
            if (TXT_NAME.Text == string.Empty || TXT_FULLNAME.Text == string.Empty || TXT_PASS.Text == string.Empty || TXT_REPASS.Text == string.Empty )
            {
                MessageBox.Show("يجب إدخال جميع البيانات", "الحقول فارقة", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

            if (TXT_REPASS.Text != TXT_PASS.Text)
            {
                MessageBox.Show("كلمة المرور غير متطابقة ", "خطأ في التحقق", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }

           
            LOG.ADD_USER(Convert.ToInt16(TXT_ID.Text),TXT_NAME.Text,TXT_FULLNAME.Text,combo_TYPE.Text,TXT_PASS.Text);
            MessageBox.Show("تمت إضافة المستخدم بنجاح", "عملية الإضافة", MessageBoxButtons.OK, MessageBoxIcon.Information);
            sqlDataSource1.Fill();
            CLEAR_TEXT_BOX(this);
            BT_SAVE.Enabled = false;
            BT_EMPTY.Enabled = true;
        }

        private void BT_EDITE_Click(object sender, EventArgs e)
        {

            LOG.EDITE_USER(Convert.ToInt16(TXT_ID.Text), TXT_NAME.Text, TXT_FULLNAME.Text, combo_TYPE.Text, TXT_PASS.Text);
            MessageBox.Show("تم تعديل بيانات المستخدم ", "عملية التعديل", MessageBoxButtons.OK, MessageBoxIcon.Information);
            sqlDataSource1.Fill();
            CLEAR_TEXT_BOX(this);

        }

        private void BT_DEL_Click(object sender, EventArgs e)
        {
          
            LOG.DEL_USER(Convert.ToInt16(TXT_ID.Text));
            MessageBox.Show("تم حذف بيانات المستخدم ", "عملية الحذف", MessageBoxButtons.OK, MessageBoxIcon.Information);
            sqlDataSource1.Fill();
            CLEAR_TEXT_BOX(this);


        }

        private void BT_EMPTY_Click(object sender, EventArgs e)
        {
            CLEAR_TEXT_BOX(this);
            GET_ID();
            BT_SAVE.Enabled = true;
            BT_DEL.Enabled = false;
            BT_EDITE.Enabled = false;

        }

        private void GRID_USER_Click(object sender, EventArgs e)
        {
            BT_SAVE.Enabled = false;
            BT_EDITE.Enabled = true;
            BT_DEL.Enabled = true;
            try
            {
                CLEAR();
                TXT_ID.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("معرف المستخدم"));
                TXT_NAME.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("إسم المستخدم"));
                TXT_FULLNAME.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("الإسم الكامل"));
                TXT_PASS.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("كلمة المرور"));
                TXT_REPASS.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("كلمة المرور"));
                combo_TYPE.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("نوع المستخدم"));
            }
            catch
            {
                return;
            }
        }

        private void GRID_USER_DoubleClick(object sender, EventArgs e)
        {
            
        }

        private void ADD_USER_Load(object sender, EventArgs e)
        {
            BT_DEL.Enabled = false;
            BT_EDITE.Enabled = false;
            BT_SAVE.Enabled = false;
        }
    }
}