using System;
using System.Data;
using System.Drawing;
using System.Windows.Forms;
using COFFEE_SHOP.PL;
using DevExpress.XtraReports.UI;

namespace COFFEE_SHOP.FORMS
{
    public partial class ORDERS_FRM : DevExpress.XtraEditors.XtraForm
    {
        public DataTable DT = new DataTable();
        REP.risept RT = new REP.risept();
        void CLEAR_TEXT_BOX(Control CN)
        {
            foreach (Control C in CN.Controls)
                if (C is Label)

                    ((Label)C).Text = "غير محجوز";

                else

                    CLEAR_TEXT_BOX(C);

        }
        void CALCULATE()
        {
            double sumNetPrice = 0;
            //gridView1
            for (int i = 0; i < gridView1.DataRowCount; ++i)
            {
                DataRow row = gridView1.GetDataRow(i);
                sumNetPrice += Convert.ToDouble(row["المبلغ الكلي"].ToString());
            }
            LAL_TOTAL.Text = sumNetPrice.ToString("SR #,##0.00");
        }
        void FILL_GRID()
        {

            DT = OPP.GET_BILL_ID_DIT(Convert.ToInt16(LBL_BILLS_ID.Text));
            GRID_BILLS.DataSource = DT;
            gridView1.Columns["رقم الطلب"].Visible = false;

        }

        BL.OPPREATION OPP = new BL.OPPREATION();

        MAIN_FRM FR;
        public ORDERS_FRM(MAIN_FRM f)
        {

            InitializeComponent();
            FR = f;
           

            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
           sqlDataSource1.Fill();
        }
         
        public void FRM_ORDERS_Load(object sender, EventArgs e)
        {
            
            FILL_GRID();
            LBL_ROOMS.Text = LBL_ROM_ID.Text;
          //  FR.splashScreenManager1.CloseWaitForm();
        }



        private void simpleButton5_Click(object sender, EventArgs e)
        {

            Close();
        }



        private void simpleButton11_Click(object sender, EventArgs e)
        {
            lbl_qun.Text = Convert.ToString(Convert.ToInt16(lbl_qun.Text) + 1);

            int X = Convert.ToInt16(lbl_qun.Text);
            var X1 = this.cardView1.GetFocusedRowCellDisplayText("السعر.......");
            ORD_PRICE = Convert.ToDecimal(X1);

            lbl_price.Text = (X * ORD_PRICE).ToString();
        }

        private void simpleButton6_Click(object sender, EventArgs e)
        {
            if (lbl_qun.Text != "0")
                lbl_qun.Text = Convert.ToString(Convert.ToInt16(lbl_qun.Text) - 1);

            int X = Convert.ToInt16(lbl_qun.Text);
            var X1 = this.cardView1.GetFocusedRowCellDisplayText("السعر.......");
            ORD_PRICE = Convert.ToDecimal(X1);

            lbl_price.Text = (X * ORD_PRICE).ToString();
        }

        public int ord_id;

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            if (DT.Rows.Count > 0)
            {

                MAIN_FRM f = new MAIN_FRM();
              
                RT.Parameters["RSP_ID"].Value = Convert.ToInt32(LBL_BILLS_ID.Text);

                if (LBL_ROM_ID.Text == "12")
                {
                    RT.Parameters["SIT_TAX"].Value = 0;
                    RT.Parameters["SIT_TAX"].Visible = false;
                    RT.Parameters["football"].Visible = false;
                    RT.Parameters["Ball_Tax"].Visible = false;

                }
                ReportPrintTool printTool = new ReportPrintTool(RT);
                printTool.PreviewForm.StartPosition = FormStartPosition.CenterScreen;
                printTool.ShowPreviewDialog();


                if (LBL_ROM_ID.Text == "1")
                {
                    FR.BT_CHECK.BackColor = Color.Green;
                    FR.labelControl1.Text = "غير محجوز";

                }
                else if (LBL_ROM_ID.Text == "2")
                {
                    FR.BT_CHECK1.BackColor = Color.Green;
                    FR.labelControl2.Text = "غير محجوز";

                }
                else if (LBL_ROM_ID.Text == "3")
                {
                    FR.BT_CHECK2.BackColor = Color.Green;
                    FR.labelControl5.Text = "غير محجوز";

                }
                else if (LBL_ROM_ID.Text == "4")
                {
                    FR.BT_CHECK4.BackColor = Color.Green;
                    FR.labelControl4.Text = "غير محجوز";

                }
                else if (LBL_ROM_ID.Text == "5")
                {
                    FR.BT_CHECK5.BackColor = Color.Green;
                    FR.labelControl3.Text = "غير محجوز";

                }
                else if (LBL_ROM_ID.Text == "6")
                {
                    FR.BT_CHECK6.BackColor = Color.Green;
                    FR.labelControl6.Text = "غير محجوز";

                }
                else if (LBL_ROM_ID.Text == "7")
                {
                    FR.BT_CHECK7.BackColor = Color.Green;
                    FR.labelControl7.Text = "غير محجوز";

                }
                else if (LBL_ROM_ID.Text == "8")
                {
                    FR.BT_CHECK8.BackColor = Color.Green;
                    FR.labelControl8.Text = "غير محجوز";

                }
                else if (LBL_ROM_ID.Text == "9")
                {
                    FR.BT_CHECK9.BackColor = Color.Green;
                    FR.labelControl9.Text = "غير محجوز";

                }
                else if (LBL_ROM_ID.Text == "10")
                {
                    FR.BT_CHECK10.BackColor = Color.Green;
                    FR.labelControl10.Text = "غير محجوز";

                }
                else
                {
                    FR.BT_CHECK11.BackColor = Color.Green;
                    FR.labelControl11.Text = "غير محجوز";
                }
            }
            else
            {
                MessageBox.Show(" ... لا يوجد طلبات لهذه الفاتورة ");
                return;
           
            }
                
            
           
             Close();
            }
        private void simpleButton12_Click(object sender, EventArgs e)
        {
            try
            {
                OPP.ADD_ORD_DIT(Convert.ToInt16(LBL_BILLS_ID.Text), ord_id, Convert.ToInt16(lbl_qun.Text), lbl_price.Text);
                FILL_GRID();
                MessageBox.Show(" ... تم إضافة الطلب");
                CALCULATE();
                lbl_qun.Text = "1";
                lbl_ord.Text = "";
                lbl_price.Text = "";
               
            }
            catch
            {
                MessageBox.Show(" ... الرجاء إختيار طلب واحد على الأقل");
            }
           
        }
        public decimal ORD_PRICE;
      
        private void simpleButton2_Click(object sender, EventArgs e)
        {
            Close();
        }

      
        private void gridControl1_Click_2(object sender, EventArgs e)
        {
      
            var id = this.cardView1.GetFocusedRowCellDisplayText("كود الطلب.......");
            ord_id = Convert.ToInt32(id);

            var red = this.cardView1.GetFocusedRowCellDisplayText("إسم الطلب.......");
            var red1 = this.cardView1.GetFocusedRowCellDisplayText("Order Name ......");
            lbl_ord.Text = Convert.ToString(red) + " / " + Convert.ToString(red1);
               

            var X1 = this.cardView1.GetFocusedRowCellDisplayText("السعر.......");
            ORD_PRICE = Convert.ToDecimal(X1);
            int X = Convert.ToInt16(lbl_qun.Text);
            lbl_price.Text = (X * ORD_PRICE).ToString();
        }

        private void label1_Click(object sender, EventArgs e)
        {

        }

        private void GRID_BILLS_Click(object sender, EventArgs e)
        {

        }

        //private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        //{

       
        //}

        //private void gridView1_PopupMenuShowing(object sender, DevExpress.XtraGrid.Views.Grid.PopupMenuShowingEventArgs e)
        //{
        //    if (e.HitInfo.InRow)
        //    {
        //        GridView VIWE = sender as GridView;
        //        VIWE.FocusedRowHandle = e.HitInfo.RowHandle;

        //        popupMenu1.ShowPopup(e.Point,VIWE );
        //    }
        //}

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            if (MessageBox.Show("هل أنت متأكد من الغاء الفاتورة ؟", " تنبيه", MessageBoxButtons.YesNo, MessageBoxIcon.Exclamation) == DialogResult.Yes)
            {
                OPP.dele_ricpt(Convert.ToInt16(LBL_BILLS_ID.Text));
                MessageBox.Show("تم إلغاء الفاتورة");
                this.Dispose();

                if (LBL_ROM_ID.Text == "12")
                {
                    RT.Parameters["SIT_TAX"].Value = 0;
                    RT.Parameters["SIT_TAX"].Visible = false;
                    RT.Parameters["football"].Visible = false;
                    RT.Parameters["Ball_Tax"].Visible = false;

                }
                ReportPrintTool printTool = new ReportPrintTool(RT);
                printTool.PreviewForm.StartPosition = FormStartPosition.CenterScreen;
                printTool.ShowPreviewDialog();


                if (LBL_ROM_ID.Text == "1")
                {
                    FR.BT_CHECK.BackColor = Color.Green;
                    FR.labelControl1.Text = "غير محجوز";

                }
                else if (LBL_ROM_ID.Text == "2")
                {
                    FR.BT_CHECK1.BackColor = Color.Green;
                    FR.labelControl2.Text = "غير محجوز";

                }
                else if (LBL_ROM_ID.Text == "3")
                {
                    FR.BT_CHECK2.BackColor = Color.Green;
                    FR.labelControl5.Text = "غير محجوز";

                }
                else if (LBL_ROM_ID.Text == "4")
                {
                    FR.BT_CHECK4.BackColor = Color.Green;
                    FR.labelControl4.Text = "غير محجوز";

                }
                else if (LBL_ROM_ID.Text == "5")
                {
                    FR.BT_CHECK5.BackColor = Color.Green;
                    FR.labelControl3.Text = "غير محجوز";

                }
                else if (LBL_ROM_ID.Text == "6")
                {
                    FR.BT_CHECK6.BackColor = Color.Green;
                    FR.labelControl6.Text = "غير محجوز";

                }
                else if (LBL_ROM_ID.Text == "7")
                {
                    FR.BT_CHECK7.BackColor = Color.Green;
                    FR.labelControl7.Text = "غير محجوز";

                }
                else if (LBL_ROM_ID.Text == "8")
                {
                    FR.BT_CHECK8.BackColor = Color.Green;
                    FR.labelControl8.Text = "غير محجوز";

                }
                else if (LBL_ROM_ID.Text == "9")
                {
                    FR.BT_CHECK9.BackColor = Color.Green;
                    FR.labelControl9.Text = "غير محجوز";

                }
                else if (LBL_ROM_ID.Text == "10")
                {
                    FR.BT_CHECK10.BackColor = Color.Green;
                    FR.labelControl10.Text = "غير محجوز";

                }
                else
                {
                    FR.BT_CHECK11.BackColor = Color.Green;
                    FR.labelControl11.Text = "غير محجوز";
                }

                this.Close();
            }

          

        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
            
            OPP.DELETE_orders_id(IDNO);
            MessageBox.Show("تم الحذف من السلة ");
            FILL_GRID();
            CALCULATE();
            simpleButton4.Enabled = false;
        }
        int IDNO;


        private void GRID_BILLS_MouseClick(object sender, MouseEventArgs e)
        {
            
            IDNO = Convert.ToInt16(this.gridView1.GetFocusedRowCellDisplayText("رقم الطلب"));
            simpleButton4.Enabled = true;

        }
    }
}