using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.SqlClient;
using COFFEE_SHOP.PL;
using COFFEE_SHOP.FORMS;


namespace COFFEE_SHOP
{
    public partial class product : DevExpress.XtraEditors.XtraForm
    {
        BL.BILLS B = new BL.BILLS();
        void FILL_CO()
        {
            CO_ID.DataSource = B.GET_GATE();
            CO_ID.DisplayMember = "CAT_NAME";
            CO_ID.ValueMember = "CAT_ID";
        }

        public void JustNumber(KeyPressEventArgs r)
        {
            if (!char.IsDigit(r.KeyChar))
            {
                if (!char.IsControl(r.KeyChar))
                {
                    if (!char.IsPunctuation(r.KeyChar))
                    {
                        if (!char.IsWhiteSpace(r.KeyChar))
                        {
                            if (!char.IsSeparator(r.KeyChar))
                                r.Handled = true;
                        }
                    }
                }
            }
        }

        BL.TRANS TR = new BL.TRANS();
        void GET_ID()
        {
            DataTable DT = new DataTable();
            DT = TR.GET_PRD_ID();
            int id = Convert.ToInt32(DT.Rows[DT.Rows.Count - 1][0]);
            TXT_ID.Text = id.ToString();
        }
        void CLEAR_TEXT_BOX(Control CN)
        {
            foreach (Control C in CN.Controls)
                if (C is TextBox)

                    ((TextBox)C).Clear();

                else

                    CLEAR_TEXT_BOX(C);
            
        }

        public product()
        {
            InitializeComponent();
            FILL_CO();

                    // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            Dispose();
            this.Close();
        }

        private void product_Load(object sender, EventArgs e)
        {
            BT_DEL.Enabled = false;
            BT_EDITE.Enabled = false;
            BT_SAVE.Enabled = false;
        }

        private void BT_SAVE_Click(object sender, EventArgs e)
        {
            TR.ADD_PRODUCT(Convert.ToInt16(TXT_ID.Text),TXT_NAME.Text,TXT_PRICE.Text,TXT_NOTE.Text,dateEdit1.DateTime,DATE_exd.DateTime,Convert.ToInt16(TXT_QUN.Text),Convert.ToInt32(CO_ID.SelectedValue));
            MessageBox.Show("تمت إضافة المنتج بنجاح", "عملية الإضافة", MessageBoxButtons.OK, MessageBoxIcon.Information);
            sqlDataSource1.Fill();
            CLEAR_TEXT_BOX(this);
            BT_DEL.Enabled = false;
            BT_EDITE.Enabled = false;
            BT_SAVE.Enabled = false;
        }

        private void BT_DEL_Click(object sender, EventArgs e)
        {
            TR.DELETE_PRODUCT(Convert.ToInt16(TXT_ID.Text));
            MessageBox.Show("تم حذف المنتج  ", "عملية الحذف", MessageBoxButtons.OK, MessageBoxIcon.Information);
            sqlDataSource1.Fill();
            CLEAR_TEXT_BOX(this);
            BT_DEL.Enabled = false;
            BT_EDITE.Enabled = false;
            BT_SAVE.Enabled = false;
        }

        private void BT_EDITE_Click(object sender, EventArgs e)
        {
            TR.EDITE_PRODUCT(Convert.ToInt16(TXT_ID.Text), TXT_NAME.Text, TXT_PRICE.Text, TXT_NOTE.Text, dateEdit1.DateTime, DATE_exd.DateTime, Convert.ToInt16(TXT_QUN.Text),Convert.ToInt32(CO_ID.SelectedValue));
            MessageBox.Show("تم تعديل بيانات المنتج ", "عملية التعديل", MessageBoxButtons.OK, MessageBoxIcon.Information);
            sqlDataSource1.Fill();
            CLEAR_TEXT_BOX(this);
            BT_DEL.Enabled = false;
            BT_EDITE.Enabled = false;
            BT_SAVE.Enabled = false;
        }

        private void panelControl3_Paint(object sender, PaintEventArgs e)
        {
           
        }

        private void BT_EXIT_Click(object sender, EventArgs e)
        {
            CLEAR_TEXT_BOX(this);
            GET_ID();

            BT_DEL.Enabled = false;
            BT_EDITE.Enabled = false;
            BT_SAVE.Enabled = true ;
        }

        private void GRID_PRD_DoubleClick(object sender, EventArgs e)
        {
          
        }

        private void GRID_PRD_Click(object sender, EventArgs e)
        {
            BT_DEL.Enabled = true ;
            BT_EDITE.Enabled = true ;
            BT_SAVE.Enabled = false;

            try
            {
                TXT_ID.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("معرف المنتج"));
                TXT_NAME.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("إسم المنتج"));
                TXT_PRICE.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("سعر المنتج"));
                TXT_NOTE.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("ملاحظة"));
                dateEdit1.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("التاريخ"));
                DATE_exd.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("تاريخ إنتهاء الصلاحية"));
                TXT_QUN.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("الكمية"));
                CO_ID.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("إسم الفئة"));
            }
            catch
            {
                return;
            }
        }

        private void TXT_PRICE_KeyPress(object sender, KeyPressEventArgs e)
        {
            JustNumber(e);
        }

        private void dateEdit1_EditValueChanged(object sender, EventArgs e)
        {

        }

        private void TXT_QUN_KeyPress(object sender, KeyPressEventArgs e)
        {
            JustNumber(e);
        }
    }
}