using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using COFFEE_SHOP.PL;
using COFFEE_SHOP.FORMS;

namespace COFFEE_SHOP
{

    public partial class sub_categore : DevExpress.XtraEditors.XtraForm
    {
        BL.BILLS B = new BL.BILLS();
        BL.TRANS TR = new BL.TRANS();
        void GET_ID()
        {
            DataTable DT = new DataTable();
            DT = TR.GET_SUP_ID();
            int id = Convert.ToInt32(DT.Rows[DT.Rows.Count - 1][0]);
            TXT_ID.Text = id.ToString();
        }
      
        public sub_categore()
        {
            InitializeComponent();
                      // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }

        private void labelControl2_Click(object sender, EventArgs e)
        {

        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {

        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            Dispose();
            Close();
        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
            TXT_ID.Text = "";
            TXT_S_CAT.Text = "";
            CO_ID.Text = "";
            GET_ID();
            BT_EDITE.Enabled = false ;
            BT_SAVE.Enabled = true;
        }

        private void simpleButton5_Click(object sender, EventArgs e)
        {
            if (CO_ID.Text == "مصروفات عمالة")
            {
                B.EDITE_S_GATE(TXT_S_CAT.Text, Convert.ToInt32(TXT_ID.Text), 2);
            }
            else
            {
                B.EDITE_S_GATE(TXT_S_CAT.Text, Convert.ToInt32(TXT_ID.Text), 1);
            }


            MessageBox.Show("تم تعديل الصرف ", "عملية التعديل", MessageBoxButtons.OK, MessageBoxIcon.Information);

            TXT_ID.Text = "";
            TXT_S_CAT.Text = "";
            CO_ID.Text = "";
            sqlDataSource1.Fill();
            BT_EDITE.Enabled = false ;
            BT_SAVE.Enabled = false;
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            if (CO_ID.Text == "مصروفات عمالة")
            {
                B.ADD_S_GATE(TXT_S_CAT.Text, Convert.ToInt32(TXT_ID.Text), 2);
            }
            else
            {
                B.ADD_S_GATE(TXT_S_CAT.Text, Convert.ToInt32(TXT_ID.Text),1);
            }
            
           
            MessageBox.Show("تمت إضافة المصروف ", "عملية الإضافة", MessageBoxButtons.OK, MessageBoxIcon.Information);

            TXT_ID.Text = "";
            TXT_S_CAT.Text = "";
            CO_ID.Text = "";
            sqlDataSource1.Fill();
            BT_EDITE.Enabled = false;
            BT_SAVE.Enabled = false;

        }

        private void panelControl3_Paint(object sender, PaintEventArgs e)
        {

        }

        private void sub_categore_Load(object sender, EventArgs e)
        {
            BT_EDITE.Enabled = false ;
            BT_SAVE.Enabled = false;
        }

        private void GRID_SUB_DoubleClick(object sender, EventArgs e)
        {
           
        }

        private void GRID_SUB_Click(object sender, EventArgs e)
        {
            BT_EDITE.Enabled = true;
            BT_SAVE.Enabled = false;
            

            try
            {
                TXT_ID.Text = "";
                TXT_S_CAT.Text = "";
                CO_ID.Text = "";

                TXT_S_CAT.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("إسم الصرف"));
                TXT_ID.Text = Convert.ToString(gridView1.GetFocusedRowCellValue("معرف الصرف"));

                if (Convert.ToString(gridView1.GetFocusedRowCellValue("الفئة")) == "1")
                {
                    CO_ID.Text = "مصروفات محل";
                }
                else
                {
                    CO_ID.Text = "مصروفات عمالة";
                }
            }
            catch
            {
                return;
            }
        }
    }
}